/** CyberWorld service worker v1.8: cache, alias, and inject unified Mars Base expansion shell v2. */
const CACHE_VERSION='fllc-v26-cyberworld-extreme2-20260617';
const STATIC_CACHE=`${CACHE_VERSION}-static`;const DYNAMIC_CACHE=`${CACHE_VERSION}-dynamic`;
const PRECACHE_ASSETS=['/','/index.html','/CyberWorld/','/CyberWorld_login/','/login/','/game/','/hub/','/mathviz/','/rgp/','/mars-mission.html','/housing.html','/hardware-lab.html','/print-lab.html','/walkthroughs.html','/cyberworld-game.html','/cyberworld-audit.html','/cyberworld-complete.html','/hangar.html','/simulator.html','/route-check.html','/cyberworld-routes.json','/css/cyberworld-unified.css','/css/cyberworld-content-enhance.css','/css/cyberworld-playtest-patches.css','/css/cyberworld-extreme.css','/js/cyberworld-unified.js','/js/cyberworld-content-enhance.js','/js/cyberworld-playtest-patches.js','/js/cyberworld-extreme.js','/wargames.html','/arcade.html','/signal-lab.html','/redops.html','/forensics.html','/intel.html','/adversaries.html','/research.html','/ai.html','/nodes.html','/games.html','/dogfight.html','/cyberworld-codex.html','/profile.html','/discuss.html','/cyberos-iso.html','/stars.html','/rpg/index.html'];
const ROUTE_ALIASES=new Map([['/login','/CyberWorld_login/'],['/signin','/CyberWorld_login/'],['/game','/game/'],['/hub','/CyberWorld/'],['/mathviz','/simulator.html'],['/hangar','/hangar.html'],['/rgp','/rpg/index.html'],['/audit','/cyberworld-audit.html'],['/mars','/mars-mission.html'],['/hardware','/hardware-lab.html'],['/housing','/housing.html'],['/print','/print-lab.html'],['/3d-print','/print-lab.html'],['/walkthroughs','/walkthroughs.html']]);
const INJECT_LINK='<link rel="stylesheet" href="/css/cyberworld-unified.css?v=20260617-unified"><link rel="stylesheet" href="/css/cyberworld-content-enhance.css?v=20260617-story"><link rel="stylesheet" href="/css/cyberworld-playtest-patches.css?v=20260617-playtest"><link rel="stylesheet" href="/css/cyberworld-extreme.css?v=20260617-extreme2">';
const INJECT_SCRIPT='<script src="/js/cyberworld-unified.js?v=20260617-extreme2" defer></script>';
self.addEventListener('install',event=>{event.waitUntil(caches.open(STATIC_CACHE).then(cache=>Promise.allSettled(PRECACHE_ASSETS.map(url=>cache.add(url).catch(()=>{})))).then(()=>self.skipWaiting()))});
self.addEventListener('activate',event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith('fllc-')&&k!==STATIC_CACHE&&k!==DYNAMIC_CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim()))});
function shouldInject(url){return url.origin===self.location.origin&&url.pathname.endsWith('.html')&&!url.pathname.startsWith('/CyberWorld_login/')&&!url.pathname.startsWith('/CyberWorld/_next/')}
async function injectHtml(response,url){const type=response.headers.get('content-type')||'';if(!type.includes('text/html')||!shouldInject(url))return response;let html=await response.text();if(!html.includes('/css/cyberworld-unified.css'))html=html.replace(/<\/head>/i,INJECT_LINK+'</head>');if(!html.includes('/js/cyberworld-unified.js'))html=html.replace(/<\/body>/i,INJECT_SCRIPT+'</body>');const headers=new Headers(response.headers);headers.set('content-type','text/html; charset=utf-8');return new Response(html,{status:response.status,statusText:response.statusText,headers})}
async function networkThenCache(request,url){const response=await fetch(request,{cache:'no-store'});const finalResponse=request.destination==='document'?await injectHtml(response.clone(),url):response.clone();caches.open(DYNAMIC_CACHE).then(c=>c.put(request,finalResponse.clone()));return finalResponse}
self.addEventListener('fetch',event=>{const{request}=event;const url=new URL(request.url);if(url.origin===self.location.origin&&request.mode==='navigate'){const key=url.pathname.replace(/\/$/,'');const target=ROUTE_ALIASES.get(key);if(target&&url.pathname!==target){event.respondWith(Response.redirect(new URL(target,self.location.origin).href,302));return}}const isGoogleFonts=url.hostname==='fonts.googleapis.com'||url.hostname==='fonts.gstatic.com';if(!isGoogleFonts&&url.origin!==self.location.origin)return;const hot=['/','/index.html','/CyberWorld/','/CyberWorld/index.html','/game/','/game/index.html','/mars-mission.html','/housing.html','/hardware-lab.html','/print-lab.html','/walkthroughs.html','/cyberworld-audit.html','/cyberworld-complete.html','/css/cyberworld-unified.css','/css/cyberworld-content-enhance.css','/css/cyberworld-playtest-patches.css','/css/cyberworld-extreme.css','/js/cyberworld-unified.js','/js/cyberworld-content-enhance.js','/js/cyberworld-playtest-patches.js','/js/cyberworld-extreme.js','/cyberworld-routes.json','/route-check.html','/simulator.html','/cyberworld-game.html','/hangar.html','/js/hangar-static.js','/dogfight.html','/js/cyber-dogfight.js'];const isHotAsset=hot.includes(url.pathname)||url.pathname.startsWith('/CyberWorld/_next/static/chunks/');if(isHotAsset){event.respondWith(networkThenCache(request,url).catch(()=>caches.match(request)));return}if(request.destination==='document'){event.respondWith(fetch(request).then(r=>injectHtml(r,url)).then(response=>{const clone=response.clone();caches.open(DYNAMIC_CACHE).then(c=>c.put(request,clone));return response}).catch(()=>caches.match(request).then(r=>r||caches.match('/index.html'))));return}event.respondWith(caches.match(request).then(cached=>cached||fetch(request).then(response=>{if(!response||response.status!==200||response.type==='error')return response;const clone=response.clone();caches.open(DYNAMIC_CACHE).then(c=>c.put(request,clone));return response}).catch(()=>{})))});
